network_ipc: add missing sys/types.h include
swupdate itself builds fine, but tests fail to build on alpine (musl
libc):

In file included from test/test_network_ipc_if.c:13:
include/network_ipc.h:145:36: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  145 | int ipc_inst_start_ext(void *priv, ssize_t size);
      |                                    ^~~~~~~
      |                                    size_t
include/network_ipc.h:163:45: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  163 |                                 void *priv, ssize_t size);
      |                                             ^~~~~~~
      |                                             size_t

ssize_t is defined in sys/types.h according to the man page, so add the
missing include.

Fixes: 4b3da83b2069 ("IPC: simplify API using a single structure")
Signed-off-by: Dominique Martinet <dominique.martinet@atmark-techno.com>