include/util.h: fix build on musl
Building on musl 1.2.4 fails with the following error/warnings:

include/util.h:211:23: error: unknown type name 'mode_t'
  211 | int mkpath(char *dir, mode_t mode);
include/util.h:269:36: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  269 | char *swupdate_time_iso8601(struct timeval *tv);

These were caused by a recent reorganization of the headers and glibc
appears more tolerant here.

Fixes: 8228b1390632 ("Reorganize includes to have smaller files")
Signed-off-by: Dominique Martinet <dominique.martinet@atmark-techno.com>